### PR TITLE
MainView: fix bottom margin

### PR DESCRIPTION
**Pull request by danrabbit**
Maybe this was a workaround for something at some point?

### CODE REVIEW

**Comment by cassidyjames** [comment]
@danrabbit it looks like the other settings panes have lists 12px from the edges, though they have sidebars. Do we want this much margin here in total, or should it be 12px from the edge of the window? Maybe that's why it was at the bottom here?

Network | This branch
---|---
Screenshot from 2020-11-05 11-24-38@2x | Screenshot from 2020-11-05 11-24-42@2x

**Comment by cassidyjames** [comment]
For comparison, here's only 12px margin on either the grid or the view (instead of on both):

Screenshot from 2020-11-05 11-26-46@2x

idk if I like it, but it does look more consistent?

**Comment by danrabbit** [comment]
I think 24px is a little more satisfying personally because:

Screenshot from 2020-11-05 10 36 56

**Review by cassidyjames — APPROVED** [review]
Yeah I also like 24 visually better, so I'll allow it. :stuck_out_tongue:

**Pull request merged**
